### ISSUE TITLE
Build Camera/GPS mast

### ISSUE THREAD

**Issue by griswaldbrooks** [victoriarobotics/victoria_mechanical#3]
Need to build mast on back of the robot to accommodate R200 and GPS.
Need to locate the camera for best FoV first.

**Comment by griswaldbrooks** [comment]
Looks like about 12 inches from the bottom of the robot is a good height for the R200.
Going to start there and should add some tuning parts for minor height and angle adjustment.

**Comment by griswaldbrooks** [comment]
First version of mock-up mast.
Two pieces of plastic hot glued to the robot.
Twisted the R200 around until you couldn't see the front of the robot.

![20170205_232823](https://cloud.githubusercontent.com/assets/390783/22638265/d0ea381e-ebfb-11e6-95a2-7b27df91b54f.jpg)
![20170205_232810](https://cloud.githubusercontent.com/assets/390783/22638264/d0e87fba-ebfb-11e6-891f-05e5a22bfe96.jpg)

**Comment by griswaldbrooks** [comment]
A flat object in front of the robot can bee seen.
![20170205_233021](https://cloud.githubusercontent.com/assets/390783/22638297/0ddd29f2-ebfc-11e6-967c-bdf0b43f5912.jpg)
![20170205_232831](https://cloud.githubusercontent.com/assets/390783/22638298/0ddd6ec6-ebfc-11e6-931d-2baeefbbbb5f.jpg)

**Comment by griswaldbrooks** [comment]
An object higher up can be seen.

![20170205_233142](https://cloud.githubusercontent.com/assets/390783/22638324/3ea74a90-ebfc-11e6-819c-aee6b6f6464f.jpg)
![20170205_233225](https://cloud.githubusercontent.com/assets/390783/22638323/3ea31d12-ebfc-11e6-851b-0bda84657ba2.jpg)

**Comment by griswaldbrooks** [comment]
But when it's pushed forward a few inches, it disappears.

![20170205_233212](https://cloud.githubusercontent.com/assets/390783/22638340/5262e530-ebfc-11e6-98e0-f4a6d7d24972.jpg)
![20170205_233203](https://cloud.githubusercontent.com/assets/390783/22638339/5262e954-ebfc-11e6-85e5-8500eec11b52.jpg)

**Comment by griswaldbrooks** [comment]
Currently, the new mast subassembly is almost done. It doesn't include a GPS mounting area.
The main mast and handle parts are done and mounted.
The r200 enclosure is done but needs to be mounted to the mast and well as covers made.

**Comment by griswaldbrooks** [comment]
The r200 is now mounted on victoria.
![victoria_r200_mounted1](https://cloud.githubusercontent.com/assets/390783/23197974/f9ab4714-f878-11e6-9c4a-110737f02330.jpeg)

View from the r200 via wifi,
![victoria_r200_rviz1](https://cloud.githubusercontent.com/assets/390783/23197975/f9aba66e-f878-11e6-9b58-5c88b1ae08fd.jpeg)

**Comment by ralphhipps** [comment]
sweet!!


Ralph

>+<
 |    /\
 |___/  \
 [_@_]   `<
 O O O          IRS!
------------------------------------------------------------------------------------
In the twenty-first century, the robot will take the place
which slave labor occupied in ancient civilization.
 -- Nikola Tesla
------------------------------------------------------------------------------------

**Comment by griswaldbrooks** [comment]
Mast construction is complete.
GPS, runstop, and r200 clear covers were installed this weekend.

![20170306_115212](https://cloud.githubusercontent.com/assets/390783/23627003/ca4ecc12-0263-11e7-8d41-90836cfe6b34.jpg)
![20170306_115159](https://cloud.githubusercontent.com/assets/390783/23627001/ca4b21e8-0263-11e7-9e33-f273f3a1404c.jpg)
![Uploading 20170306_115204.jpg…]()
![20170306_115208](https://cloud.githubusercontent.com/assets/390783/23627002/ca4be3e4-0263-11e7-8946-c097eb795649.jpg)

There are many additional little things to fix and add, which will be outlined in other tickets.

They include:
- Fixing bolt holes on r200 covers #11
- Sealing r200 with silicon caulking #13
- Add small desiccant pack to r200 #12
- Replace zip ties with cable mounts/organizers #14
- Print runstop enclosure for water protection #15
- Wire runstop into Teensy board (or TRex?) victoriarobotics/victoria_electrical#15
- Update/create design files #16 #17 #18
