### ISSUE TITLE
Design bumper

### ISSUE THREAD

**Issue by griswaldbrooks** [victoriarobotics/victoria_mechanical#4]

**Comment by griswaldbrooks** [comment]
So, I did a quick test with the neato hall effect sensor to see what kind of responses there were.
There were several testing conditions.
The primary one was voltage vs distance, but I also tested three different magnet sizes that I have, and the presence of a metal slug that is usually behind the sensor that channels the flux through the sensor.

Here is a chart of the response:
(https://github.com/victoriarobotics/victoria_mechanical/files/784392/hall_effect_data1.xlsx)

Obviously the largest disc magnet with the slug gives the best response but if that interferes with the compass I believe the small disc with slug would suffice. 
I feel like the ball magnet is going to be trouble. In general, we should use the slug.

Here is the data:
![hall_effect_response_chart1](https://cloud.githubusercontent.com/assets/390783/23084318/927413a6-f516-11e6-941f-db948e13188f.png)
[hall_effect_data1.xlsx]

Picture of the sensor without slug:
![20170217_134656](https://cloud.githubusercontent.com/assets/390783/23084661/4c848f68-f518-11e6-8672-1f6445b2590f.jpg)

Picture of the sensor with slug:
![20170217_134704](https://cloud.githubusercontent.com/assets/390783/23084674/5d44fff4-f518-11e6-84f2-a83929d81445.jpg)

Picture of the magnets tested and the testing blocks I used.
![20170217_134914](https://cloud.githubusercontent.com/assets/390783/23084679/6a6a05ee-f518-11e6-9497-51a02ae4e606.jpg)

The discs were of 1 inch and 3/8 inch diameter and the ball was 3/16 inch diameter.

**Comment by griswaldbrooks** [comment]
Forgot to mention, the sensor was powered with 5V and the baselines were:
No magnet, No slug: 2.494V
No magnet, Slug: 2.579V

**Comment by griswaldbrooks** [comment]
I was told that the new version of the sensor (I didn't realize I was using the old version) uses a more sensitive hall effect. I'll have to retest.

**Comment by markwomack** [comment]
Looks like Small Disc w/slug, allowing for an inch or more of movement by the bumper arm?  Seems like that will be sensitive enough to know we ran into something, but not too noisy if we bump around.  Assuming there is a spring on the bumper arm...

**Comment by griswaldbrooks** [comment]
Right, well, we'd be comparing Small Disc with Slug at 1 inch: 2.768 V to No Magnet with Slug: 2.579
So, it'll probably be fine, depending on testing with vibrations.
I think the mechanism is sound, and we'll get things as close as we can, but we can also swap sensors, adjust their position, and swap magnets if we have a problem without fundamentally overhauling the mechanism.

**Comment by markwomack** [comment]
I was thinking it would be more like 3.8v (when very close, .25) compared to 2.75v (when 1 inch removed).  Maybe I don't understand that chart.

**Comment by griswaldbrooks** [comment]
Consider bumper extended vs bumper compressed.
![bumper_extended1](https://cloud.githubusercontent.com/assets/390783/23087840/37bcbd1c-f52c-11e6-83de-f844c36138ce.png)
![bumper_compressed1](https://cloud.githubusercontent.com/assets/390783/23087841/37beb7de-f52c-11e6-928a-f0173885b40c.png)

The sensor is inside the robot, facing orthogonal to the motion of the magnet.
Therefore it only sees the magnet or not.
The distance is meant for how close we can get the sensor and magnet together in one of these states and still allow the robot to be opened up.
I guess the magnet can be very close to the shell, since it only moves relative to it, but the sensor can only be so close.

**Comment by griswaldbrooks** [comment]
An overhead view would look something like this.
![bumper_compressed3](https://cloud.githubusercontent.com/assets/390783/23088064/f59ceb9e-f52d-11e6-9625-5c8bd588f4d5.png)

The distance here is what I was testing.
![bumper_extended3](https://cloud.githubusercontent.com/assets/390783/23088065/f5a2a4ee-f52d-11e6-8d2d-dadacdcce153.png)

**Comment by griswaldbrooks** [comment]
Updated test with the other sensor.

![hall_effect_response_chart2](https://cloud.githubusercontent.com/assets/390783/23090067/93a69766-f549-11e6-8235-073ceeacf69f.png)
[hall_effect_data1.xlsx](https://github.com/victoriarobotics/victoria_mechanical/files/784740/hall_effect_data1.xlsx)

**Comment by griswaldbrooks** [comment]
So as a quick test, I "mounted" the hall effect sensor in the robot
![20170217_200519](https://cloud.githubusercontent.com/assets/390783/23090242/3588831a-f54e-11e6-868d-0df91df51a38.jpg)
![20170217_200504](https://cloud.githubusercontent.com/assets/390783/23090243/358b8c7c-f54e-11e6-9bf4-f386968b731b.jpg)

It's inset by the amount it is because the upper shell is inset
![20170217_200536](https://cloud.githubusercontent.com/assets/390783/23090249/60a3b042-f54e-11e6-8915-24ccdad93d50.jpg)

So, using a spacer about 0.2 inches thick


![20170217_200543](https://cloud.githubusercontent.com/assets/390783/23090262/c3926036-f54e-11e6-8ff4-827715581062.jpg)


I placed the small disc magnet over the "new" sensor until I got the max response.
![20170217_200555](https://cloud.githubusercontent.com/assets/390783/23090264/c66ba33a-f54e-11e6-9f22-093356514b13.jpg)


Then I moved it a bit to the left. The results are:

| Displacement (in) | Voltage (V) |
|---------------------|-------------|
| 0                            | 1.83           |
| 0.25                       | 1.5             | 
| 0.5                         | 1.09           |

Given these results, I'm guessing we can build whatever is practical and calibrate it.

**Comment by griswaldbrooks** [comment]
Bumper is installed, no hall sensors installed 

https://youtu.be/ipIWtrX_vfM

**Comment by griswaldbrooks** [comment]
Hall sensors installed
https://youtu.be/vJRPw-XxklI

**Comment by griswaldbrooks** [comment]
Pictures of the sensor on the inside.
Still need to crimp new connectors and get the design files up and then this can be closed.

![20170226_232825 1](https://cloud.githubusercontent.com/assets/390783/23375027/a0df6e64-fcdb-11e6-9482-161bbc4a454a.jpg)
![20170226_232821 1](https://cloud.githubusercontent.com/assets/390783/23375033/a9742dda-fcdb-11e6-8211-0155357b4caa.jpg)
![20170226_232815 1](https://cloud.githubusercontent.com/assets/390783/23375045/b1fa9458-fcdb-11e6-865e-71dcbdebad49.jpg)

**Comment by griswaldbrooks** [comment]
Note, right now when the bumper is extended (not bumping), the magnet and the hall sensor are aligned and receiving full signal. The advantage of doing it this way versus the other way is that if the cover (top shell) is removed, the robot will think it's bumper is compressed (bumping) and will not run.

**Comment by griswaldbrooks** [comment]
As the integration of the sensors, electrically, is going to be addressed in https://github.com/victoriarobotics/victoria_electrical/issues/9
I'm going to close this one.
